services:
  scraper:
    env_file: .env
    build:
      context: .
    user: root
    container_name: healthcheck_scraper
    volumes:
      - .:/project/
      - ./sessions/:/project/sessions/
      - ./logs/:/var/log/
    tty: true
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: healthcheck_db
    env_file: ./docker/.env-postgres
    ports:
      - "15433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  minio:
    image: minio/minio
    container_name: healthcheck_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  frontend:
    build:
      context: ./web/client
    container_name: ehfake_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
  backend:
    build:
      context: ./web/server
    container_name: ehfake_backend
    ports:
      - "8000:8000"
    depends_on:
      - minio
      
volumes:
  pgdata:
  minio_data:
