blank_issues_enabled: false
contact_links:
  - name: 📚 Documentação do Projeto
    url: https://eh-fake.github.io/docs/land/index.html
    about: Leia a documentação completa antes de contribuir
  - name: 📚 Tutorial de Contribuição com Spiders e Plays existentes
    url: https://github.com/EH-FAKE/check-up/blob/develop/TUTORIAL_SPIDERS_PLAYS.md
    about: Leia o tutorial de contribuição com spiders e plays existentes antes de contribuir
  - name: 📚 Tutorial de Contribuição com novos Spiders e Plays
    url: https://github.com/EH-FAKE/check-up/blob/develop/TUTORIAL_CRIACAO_DO_ZERO.md
    about: Leia o tutorial de contribuição com novos spiders e plays antes de contribuir